name: Vulnerable PR job

on:
  pull_request_target:

jobs:
  vulnerable_print_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo ${{ github.event.pull_request.title }} >> /tmp/pull_requests_history.txt
    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
