name: Vulnerable PR job

on:
  pull_request:

jobs:
  vulnerable_print_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo ${{ github.event.pull_request.title }}
    env:
      super_secret: ${{ secrets.SUPER_SECRET }}
